# Gauß-Algorithmus

### Implementierung

In [1]:
import numpy as np

In [2]:
def gauss_elimination(A, b):
    
    """Main function for Gauss Elimination algorithm"""
    
    A, b = upper_triangle(A, b)
    return backwards_insert(A, b)

In [3]:
def upper_triangle(A, b):
    
    """Transforms the extended coefficient matrix $A | b$ into an upper triangular form"""
    
    m, n = np.shape(A)
    M = np.array(np.concatenate((A, np.array([b]).T), axis=1), dtype=np.float64)
    for j in range(0, n-1) :
        a = abs(M[j, j])
        for i in range(j, m) :
            if abs(M[i,j]) >= a : 
                r = i
                a = abs(M[i, j])
        if a == 0 :
            continue
        else :
            M[[j,r]] = M[[r,j]]
            for i in range(j+1, m) :
                l = M[i,j] / M[j,j]
                M[i] = M[i] - l * M[j]
    return (M[:,[k for k in range(0, len(A))]], M[:, len(b)])

In [4]:
def backwards_insert(A, b):
    
    """Solves a system of an upper triangular matrix A and a vector b by backwards insertion"""
    
    n = len(b)
    x = []
    for i in range(n, 0, -1) :
        s = 0
        for j in range(i, n) :
            s += A[i-1, j] * x[n-j-1]
        val = 1 / A[i-1,i-1] * (b[i-1] - s)
        x.append(val)
    return list(reversed(x))

### Beispiel: Das implementierte Verfahren funktioniert nur bei Matrizen mit vollem Rang

In [5]:
A = np.array([[2, 4, 2], [2, 12, 7], [1, 10, 6]])
b = np.array([-12, -5, 1])

print(A)
print(b)

[[ 2  4  2]
 [ 2 12  7]
 [ 1 10  6]]
[-12  -5   1]


Die Matrix kann ich Zeilenstufenform gebracht werden:

In [6]:
upper_triangle(A,b)

(array([[ 2., 12.,  7.],
        [ 0., -8., -5.],
        [ 0.,  0.,  0.]]), array([-5., -7.,  0.]))

Das Gleichungssystem kann aber nicht gelöst werden, da durch Null dividiert werden müsste:

In [7]:
gauss_elimination(A,b)

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in double_scalars
  # This is added back by InteractiveShellApp.init_path()
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in double_scalars
  # This is added back by InteractiveShellApp.init_path()


[nan, nan, nan]

Auch die Numpy-Funktion kann das Gleichungssystem nicht lösen:

In [8]:
np.linalg.solve(A,b)

LinAlgError: Singular matrix

### Test, ob die Ergebnisse des hier implementierten Verfahrens mit denen der Numpy-Funktion übereinstimmen

In [9]:
N = 100
k = 1

while k < N + 1 :
    
    A_random = np.random.rand(10,10)
    b_random = np.random.rand(10)
    
    assert np.allclose(gauss_elimination(A_random, b_random), np.linalg.solve(A_random, b_random))
    
    k += 1