# Beispiel: Anwendung Linearer Algebra & Numerik

#### Zwei gekoppelte harmonische Oszillatoren der Masse $m$ mit Federkonstante $k$.

\begin{align*}
    m \ddot{x}_1 &= k (x_2 - x_1) - k x_1 \\
    m \ddot{x}_2 &= k (x_1 - x_2)
\end{align*}

Rate Ansatz: $x_i = A_i \sin(\omega t + \varphi)$. Einsetzen ergibt:

\begin{align*}
    - m \omega^2 A_1 &= k (A_2 - A_1) - k A_1 \\
    - m \omega^2 A_2 &= k (A_1 - A_2)
\end{align*}

In Matrixform:

\begin{align*}
    \begin{pmatrix}
        2 & -1 \\
        -1 & 1
    \end{pmatrix}   
    \begin{pmatrix}
        A_1 \\
        A_2
    \end{pmatrix}
    =
    \underbrace{\frac{m \omega^2}{k}}_{=: \lambda}
    \begin{pmatrix}
        A_1 \\
        A_2
    \end{pmatrix}
\end{align*}

\begin{align*}
    \implies \quad M \cdot \vec{A} = \lambda \cdot \vec{A}
\end{align*}


In [1]:
import numpy as np

M = np.array([[2, -1], [-1, 1]])
M

array([[ 2, -1],
       [-1,  1]])

In [2]:
evals, evects = np.linalg.eig(M)

In [3]:
evals

array([2.61803399, 0.38196601])

In [4]:
evects

array([[ 0.85065081,  0.52573111],
       [-0.52573111,  0.85065081]])

Sei $\tilde{\lambda}$, $\tilde{A}$ das numerische Ergebnis. Betrachte
\begin{align*}
    M \cdot \tilde{A} - \tilde{\lambda} \tilde{A}
\end{align*}

In [5]:
a1 = np.array([evects[0,0], evects[1,0]])
a1

array([ 0.85065081, -0.52573111])

In [6]:
a2 = np.array([evects[0,1], evects[1,1]])
a2

array([0.52573111, 0.85065081])

In [7]:
np.dot(M, a1) - evals[0] * a1

array([ 0.00000000e+00, -2.22044605e-16])

In [8]:
np.dot(M, a2) - evals[1] * a2

array([-1.66533454e-16,  5.55111512e-17])

Berechnung der Kreisfrequenz über Eigenwerte:

\begin{align*}
    \omega = \sqrt{\frac{k \lambda}{m}}
\end{align*}

#### $n$ gekoppelte harmonsiche Oszillatoren der Massen $m$ mit Federkonstante $k$.

Betrachte $n = 10$.

In [9]:
import scipy.sparse
import scipy.sparse.linalg
from scipy.sparse import csr_matrix

S = scipy.sparse.rand(10, 10, density=0.5, format="csr", random_state=73)
S

<10x10 sparse matrix of type '<class 'numpy.float64'>'
	with 50 stored elements in Compressed Sparse Row format>

In [10]:
S.toarray()

array([[0.54769583, 0.        , 0.83568684, 0.19868729, 0.        ,
        0.        , 0.54228553, 0.8989356 , 0.91786425, 0.33223246],
       [0.        , 0.        , 0.42382329, 0.65514392, 0.        ,
        0.55667029, 0.        , 0.        , 0.        , 0.        ],
       [0.2094512 , 0.        , 0.        , 0.0303005 , 0.91527261,
        0.        , 0.        , 0.12525697, 0.93230303, 0.13136246],
       [0.50066768, 0.        , 0.54040181, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.15136982, 0.64520976, 0.86130727, 0.15740563, 0.        ,
        0.61391017, 0.        , 0.12956879, 0.        , 0.        ],
       [0.65658902, 0.        , 0.97566229, 0.31876264, 0.41328986,
        0.        , 0.        , 0.        , 0.        , 0.18248339],
       [0.76963708, 0.        , 0.40492701, 0.        , 0.        ,
        0.89019428, 0.05211898, 0.48384637, 0.51107984, 0.        ],
       [0.        , 0.75146609, 0.       

In [11]:
np.shape(S)

(10, 10)

In [12]:
w, v = scipy.sparse.linalg.eigs(S, k = 8)

In [13]:
w

array([ 2.51490248+0.j        ,  0.63797751+0.j        ,
       -0.1210188 +1.01956873j, -0.1210188 -1.01956873j,
       -0.30109073+0.32566063j, -0.30109073-0.32566063j,
       -0.7070164 +0.17249934j, -0.7070164 -0.17249934j])

In [14]:
v

array([[-0.52535211+0.j        , -0.52555023+0.j        ,
        -0.27539519-0.29674927j, -0.27539519+0.29674927j,
        -0.06574231-0.03352293j, -0.06574231+0.03352293j,
        -0.55958466-0.02566663j, -0.55958466+0.02566663j],
       [-0.16692213+0.j        ,  0.04312969+0.j        ,
         0.11449615+0.33284178j,  0.11449615-0.33284178j,
        -0.03406834-0.1679515j , -0.03406834+0.1679515j ,
        -0.25703235-0.21369232j, -0.25703235+0.21369232j],
       [-0.29027269+0.j        ,  0.2572407 +0.j        ,
         0.10053358-0.28618807j,  0.10053358+0.28618807j,
         0.06439674-0.07156063j,  0.06439674+0.07156063j,
         0.48373159-0.19955343j,  0.48373159+0.19955343j],
       [-0.16696103+0.j        , -0.19454083+0.j        ,
        -0.28368556+0.11562166j, -0.28368556-0.11562166j,
        -0.09469347+0.08176076j, -0.09469347-0.08176076j,
        -0.01426979+0.16722096j, -0.01426979-0.16722096j],
       [-0.2736478 +0.j        ,  0.27552697+0.j        ,
         0

In [15]:
SM = S.todense()

In [16]:
SM

matrix([[0.54769583, 0.        , 0.83568684, 0.19868729, 0.        ,
         0.        , 0.54228553, 0.8989356 , 0.91786425, 0.33223246],
        [0.        , 0.        , 0.42382329, 0.65514392, 0.        ,
         0.55667029, 0.        , 0.        , 0.        , 0.        ],
        [0.2094512 , 0.        , 0.        , 0.0303005 , 0.91527261,
         0.        , 0.        , 0.12525697, 0.93230303, 0.13136246],
        [0.50066768, 0.        , 0.54040181, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.15136982, 0.64520976, 0.86130727, 0.15740563, 0.        ,
         0.61391017, 0.        , 0.12956879, 0.        , 0.        ],
        [0.65658902, 0.        , 0.97566229, 0.31876264, 0.41328986,
         0.        , 0.        , 0.        , 0.        , 0.18248339],
        [0.76963708, 0.        , 0.40492701, 0.        , 0.        ,
         0.89019428, 0.05211898, 0.48384637, 0.51107984, 0.        ],
        [0.        , 0.7514

In [17]:
np.linalg.eig(SM)

(array([ 2.51490248+0.j        , -0.1210188 +1.01956873j,
        -0.1210188 -1.01956873j,  0.63797751+0.j        ,
        -0.7070164 +0.17249934j, -0.7070164 -0.17249934j,
        -0.30109073+0.32566063j, -0.30109073-0.32566063j,
        -0.04426442+0.42016773j, -0.04426442-0.42016773j]),
 matrix([[ 0.52535211+0.j        ,  0.08902965+0.39493843j,
           0.08902965-0.39493843j, -0.52555023+0.j        ,
          -0.56017298+0.j        , -0.56017298-0.j        ,
          -0.07066656+0.02126206j, -0.07066656-0.02126206j,
           0.01128258+0.01692112j,  0.01128258-0.01692112j],
         [ 0.16692213+0.j        ,  0.06822223-0.34530963j,
           0.06822223+0.34530963j,  0.04312969+0.j        ,
          -0.2665536 -0.2016909j , -0.2665536 +0.2016909j ,
          -0.14077275-0.09773123j, -0.14077275+0.09773123j,
          -0.18408818+0.12425857j, -0.18408818-0.12425857j],
         [ 0.29027269+0.j        , -0.23070573+0.19694028j,
          -0.23070573-0.19694028j,  0.2572407 