# Gauß-Jordan-Algorithmus

### Implementierung

In [1]:
import numpy as np

In [2]:
def gauss_jordan(A) :
    
    n = len(A)
    M = np.array(np.concatenate((A, np.identity(n)), axis=1), dtype=np.float64)
    
    """ Transforms the extended coefficient matrix $A | 1$ into an upper triangular form $\tilde{A} | \tilde{B}$ """
    
    for j in range(0, n-1) :
        a = abs(M[j, j])
        for i in range(j, n) :
            if abs(M[i,j]) >= a : 
                r = i
                a = abs(M[i, j])
        if a == 0 :
            continue
        else :
            M[[j,r]] = M[[r,j]]
            for i in range(j+1, n) :
                l = M[i,j] / M[j,j]
                M[i] = M[i] - l * M[j]
    
    """ Tests, if $rank(A) = n$ """   
    
    if M[n-1,n-1] == 0 :
        print("Matrix ist singulär!")
        raise np.linalg.LinAlgError
    
    """ Transforms $\tilde{A} | \tilde{B}$ into $1 | B$ """       
    
    for j in range(n-1, -1, -1) :
        M[j] = M[j] / M[j, j]
        for i in range(j-1, -1, -1) :
            l = M[i,j] / M[j, j]  
            M[i] = M[i] - l * M[j]
    
    return M[:,  [k for k in range(len(A), len(M[0]))]]

### Beispiele

In [3]:
A = np.array([[1,2,0,0],[0,2,1,1],[0,1,1,0], [1,2,1,1]])
A

array([[1, 2, 0, 0],
       [0, 2, 1, 1],
       [0, 1, 1, 0],
       [1, 2, 1, 1]])

In [4]:
gauss_jordan(A)

array([[ 0. , -1. ,  0. ,  1. ],
       [ 0.5,  0.5,  0. , -0.5],
       [-0.5, -0.5,  1. ,  0.5],
       [-0.5,  0.5, -1. ,  0.5]])

In [5]:
np.dot(A, gauss_jordan(A))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.dot(gauss_jordan(A), A)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
B = np.array([[1, 2],[3, 4]])
B

array([[1, 2],
       [3, 4]])

In [8]:
gauss_jordan(B)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [9]:
np.dot(B, gauss_jordan(B))

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [10]:
np.dot(gauss_jordan(B), B)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [11]:
C = np.array([[1, 2],[2, 4]])
C

array([[1, 2],
       [2, 4]])

In [12]:
gauss_jordan(C)

Matrix ist singulär!


LinAlgError: 

In [13]:
D = np.array([[0, 1, -4], [1, 2, -1], [1, 1, 2]])
D

array([[ 0,  1, -4],
       [ 1,  2, -1],
       [ 1,  1,  2]])

In [14]:
gauss_jordan(D)

array([[ 5., -6.,  7.],
       [-3.,  4., -4.],
       [-1.,  1., -1.]])

In [15]:
np.dot(D, gauss_jordan(D))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.dot(gauss_jordan(D), D)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])