# Numerik eines linearen Gleichungssystems

### Beispiel

Pivot $\varepsilon$

\begin{align*}
    \begin{pmatrix}
        \varepsilon & 1 \\
        1 & 2 
    \end{pmatrix}
    \begin{pmatrix}
        x \\
        y 
    \end{pmatrix}
    = \begin{pmatrix} 1 \\ 1 \end{pmatrix}
\end{align*}

\begin{align*}
    \left(\begin{array}{c c | c}
        \varepsilon & 1 & 1\\
        0 & 2 - \frac{1}{\varepsilon} & 1 - \frac{1}{\varepsilon}
    \end{array}\right)
\end{align*}

\begin{align*}
    y = \frac{1 - \frac{1}{\varepsilon}}{2 - \frac{1}{\varepsilon}} \quad , \quad x = \frac{1 - y}{\varepsilon}
\end{align*}

Pivot $2$

\begin{align*}
    \left(\begin{array}{c c | c}
        2 & 1 & 1\\
        1 & \varepsilon & 1
    \end{array}\right)
\end{align*}

\begin{align*}
    \left(\begin{array}{c c | c}
        2 & 1 & 1\\
        0 & \varepsilon - \frac{1}{2} & \frac{1}{2}
    \end{array}\right)
\end{align*}

\begin{align*}
    x = \frac{1}{2 \varepsilon - 1} \quad , \quad y = \frac{1 - x}{2}
\end{align*}

### Auswertung

In [1]:
import numpy as np

In [2]:
x_eps = np.array([])
y_eps = np.array([])

x_p2 = np.array([])
y_p2 = np.array([])

for k in range(1,5):
    
    n       = 4 ** k
    eps     = 2 ** (-n)
    
    y_e     = round((1 - 1/eps) / (2 - 1/eps), 15)
    x_e     = round((1 - y_e) / eps, 15)
    y_eps   = np.append(y_eps, y_e)
    x_eps   = np.append(x_eps, x_e)
    
    
    x_2     = round(1 / (2 * eps - 1), 14)
    y_2     = round((1 - x_2) / 2, 14)
    x_p2    = np.append(x_p2, x_2)
    y_p2    = np.append(y_p2, y_2)

In [3]:
y_p2

array([1.07142857, 1.00001526, 1.        , 1.        ])

In [4]:
y_eps

array([1.07142857, 1.00001526, 1.        , 1.        ])

In [5]:
x_p2

array([-1.14285714, -1.00003052, -1.        , -1.        ])

In [6]:
x_eps

array([-1.14285714, -1.00003052,  0.        ,  0.        ])

In [7]:
# k = 3

n   = 4 ** 3
eps = 2 **(-n)

eps

5.421010862427522e-20

In [8]:
1 / eps

1.8446744073709552e+19

\begin{align*}
    \frac{1 - \frac{1}{\varepsilon}}{2 - \frac{1}{\varepsilon}} \approx 
    \frac{1 - \frac{1}{\varepsilon}}{1 - \frac{1}{\varepsilon}} = 1
\end{align*}

In [9]:
(1 - 1/eps) / (2 - 1/eps)

1.0

In [10]:
(1 - (1 - 1/eps) / (2 - 1/eps)) / eps

0.0